gtest: fix gtest compilation error
This commit fix below compilation error:

test_snap_dp_map.cc:67:2:   required from here
/usr/local/gtest/include/gtest/gtest.h:1552:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
 1552 |   if (lhs == rhs) {
      |       ~~~~^~~~~~

Signe-off-by: Tom Wu <tomwu@nvidia.com>